#!/bin/sh

#
# A shell included with this package that will make it easier to alter the
# $PATH environment variable to point to a virtual runtime environment previously
# created.
#
# As opposed to manually having to call ``export`` with the location
#

vre_path() {
    DIR="$HOME/.cora/$1"
    if [ -d "$DIR" ]; then
        echo "$DIR"
    fi
}

vre_bin="$(vre_path)/runtime/bin/"

if [ ! -e "$vre_bin" ]; then
    echo "Did not find virtual runtime directory: $HOME/.cora/$1"
else
    export PATH=$vre_bin:$PATH
fi
